name: msnbasexic
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-msnbase=2.26.0
  - r-base=4.3.1
  - r-ggplot2=3.4.3
  - r-optparse=1.7.3
  - r-pracma=2.4.2
  - r-readr=2.1.4
  - r-jsonlite=1.8.7
  - r-glue=1.6.2
